EP/EA/urls.py
from django.urls import path
from . import views
app_name = 'EA'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('search/', views.search, name='search'),
]


urlpatterns += [
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author-detail'),
]


urlpatterns += [
    path('api/books/', views.BookListAPIView.as_view(), name='api-book-list'),
    path('api/books/<int:pk>/', views.BookDetailAPIView.as_view(), name='api-book-detail'),
    path('api/authors/', views.AuthorListAPIView.as_view(), name='api-author-list'),
    path('api/authors/<int:pk>/', views.AuthorDetailAPIView.as_view(), name='api-author-detail'),
    path('api/authors/create', views.AuthorListCreateAPIView.as_view(), name='api-author-create'),
    path('api/books/create', views.BookListCreateAPIView.as_view(), name='api-book-create'),
    path('api/books/search/', views.BookSearchAPIView.as_view(), name='api-book-search'),
]

EP/EP/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

from django.urls import include
from django.urls import path
urlpatterns += [
    path('EA/', include('EA.urls', namespace='EA')),
]


from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/EA/', permanent=True)),
]

urlpatterns += [
path('accounts/', include('django.contrib.auth.urls')),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EP/EA/models.py
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import AbstractUser
import re
class CustomUser(AbstractUser):
    first_name = models.CharField(max_length=150, blank=False, verbose_name='Имя')
    last_name = models.CharField(max_length=150, blank=False, verbose_name='Фамилия')
    username = models.CharField(max_length=150, unique=True, blank=False, verbose_name='Логин')
    email = models.EmailField(unique=True, blank=False, verbose_name='Электронная почта')
    middle_name = models.CharField(max_length=150, blank=False, verbose_name='Отчество')
    password1 = models.CharField(max_length=128, blank=False, null=True, verbose_name='Пароль')
    password2 = models.CharField(max_length=128, blank=False, null=True, verbose_name='Повтор пароля')
    consent = models.BooleanField(default=False, verbose_name='Я соглашаюсь на обработку моих персональных данных')

    groups = models.ManyToManyField(
        'auth.Group',
        related_name='groups_set',
        blank=True,
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
        verbose_name='groups',
    )

    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='customuser_set',
        blank=True,
        help_text='Specific permissions for this user.',
        verbose_name='user permissions',
    )

    def clean(self):
        super().clean()
        if not re.match(r'^[А-Яа-яЁёs-]*$', self.last_name):
            raise ValidationError('Фамилия должна содержать только кириллические буквы, пробелы и дефисы.')
        if not re.match(r'^[А-Яа-яЁёs-]*$', self.first_name):
            raise ValidationError('Имя должно содержать только кириллические буквы, пробелы и дефисы.')
        if self.middle_name and not re.match(r'^[А-Яа-яЁёs-]*$', self.middle_name):
            raise ValidationError('Отчество должно содержать только кириллические буквы, пробелы и дефисы.')
        if not self.consent:
            raise ValidationError('Необходимо согласие на обработку персональных данных.')


# Модель, представляющая жанр книги (например, научная фантастика, документальная литература):
from django.db import models
from datetime import date
class Genre(models.Model):
    name = models.CharField(max_length=200, help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)")

    # Строка для представления объекта модели (на сайте администратора и т. д.):
    def __str__(self):

        return self.name


# Модель, представляющая язык (например, английский, французский, японский и т. д.):
from django.db.models import UniqueConstraint
from django.db.models.functions import Lower
class Language(models.Model):
    name = models.CharField(max_length=200,
                            unique=True,
                            help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    # Возвращение URL-адреса для доступа к определенному языковому экземпляру:
    def get_absolute_url(self):

        return reverse('language-detail', args=[str(self.id)])

    def __str__(self):

        return self.name

    class Meta:
        constraints = [
            UniqueConstraint(
                Lower('name'),
                name='language_name_case_insensitive_unique',
                violation_error_message = "Language already exists (case insensitive match)"
            ),
        ]


# Модель, представляющая автора:
class Author(models.Model):

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)
    biography = models.TextField(max_length=2000, help_text="Enter a brief biography of the author", blank=True, null=True)
    works = models.TextField(max_length=2000, help_text="List of works by the author", blank=True, null=True)
    notable_achievements = models.TextField(max_length=2000, help_text="Significant achievements of the author", blank=True, null=True)

    # Возвращение URL-адреса для доступа к конкретному экземпляру автора:
    def get_absolute_url(self):

        return reverse('author-detail', args=[str(self.id)])

    class Meta:
        ordering = ['last_name']
        unique_together = (('first_name', 'last_name'),)

    def __str__(self):

        return '%s, %s' % (self.last_name, self.first_name)



class Publisher(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


# Модель, представляющая книгу (но не конкретный экземпляр книги):
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
class Book(models.Model):
    FICTION = 'fiction'
    TEXTBOOK = 'textbook'
    CATEGORY_CHOICES = [
        (FICTION, 'Художественное произведение'),
        (TEXTBOOK, 'Учебник'),
    ]

    title = models.CharField(max_length=200, null=True)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book", null=True)
    isbn = models.CharField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    language = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True)
    publication_year = models.IntegerField(null=True, help_text="Enter the year of publication (1000-9999)", validators=[MinValueValidator(1000), MaxValueValidator(9999)])
    category = models.CharField(null=True, max_length=100, help_text="Enter the category of the book")
    publisher = models.CharField(null=True, max_length=100, help_text="Enter the publisher of the book")
    cover_image = models.ImageField(upload_to='covers/', blank=True, null=True, help_text="Upload the cover image of the book")
    text_file = models.FileField(upload_to='books/', blank=True, null=True, help_text="Upload the text file of the book")
    title_type = models.CharField(blank=True, null=True, max_length=20)

    class Meta:
        unique_together = (('title', 'author', 'publication_year', 'publisher'),)  # Уникальность по указанным полям

    def __str__(self):

        return self.title

    def get_absolute_url(self):

        return reverse('book-detail', args=[str(self.id)])

    # Создание строки для Жанра. Это необходимо для отображения жанра в Админе:
    def display_genre(self):

        return ', '.join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_description = 'Genre'


class Edition(models.Model):
    book = models.ForeignKey(Book, related_name='editions', on_delete=models.CASCADE)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    year = models.IntegerField()

    class Meta:
        unique_together = ('book', 'publisher', 'year')

    def __str__(self):
        return f"{self.book.title} - {self.publisher.name} ({self.year})"


# Модель, представляющая собой конкретный экземпляр книги (т. е. тот, который можно взять в библиотеке):
import uuid
class BookInstance(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book availability')

    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Set book as returned"),)


    def __str__(self):

        return '%s (%s)' % (self.id,self.book.title)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

EP/EA/forms.py
from django import forms
from .models import CustomUser
class CustomUserCreationForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('last_name', 'first_name', 'middle_name', 'username', 'email', 'password1', 'password2', 'consent')


from django.contrib.auth.forms import AuthenticationForm
class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password']


class SearchForm(forms.Form):
    query = forms.CharField(label='Поиск', max_length=100)

EP/EA/views.py
from .models import Book, Author, BookInstance, Genre

# Функция отображения для домашней страницы сайта.
def index(request):

    # Генерация "количеств" некоторых главных объектов:
    num_books=Book.objects.all().count()
    num_instances=BookInstance.objects.all().count()
    # Доступные книги (статус = 'a')
    num_instances_available=BookInstance.objects.filter(status__exact='a').count()
    num_authors=Author.objects.count()  # Метод 'all()' применён по умолчанию.
    num_books_word=Book.objects.filter(title__icontains='дети').count()
    num_genres=Genre.objects.all().count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    # Отрисовка HTML-шаблона index.html с данными внутри переменной контекста context:
    return render(
        request,
        'index.html',
        context={'num_books':num_books,'num_instances':num_instances,'num_instances_available':num_instances_available,'num_authors':num_authors, 'num_genres':num_genres, 'num_books_word':num_books_word, 'num_visits':num_visits},
    )


from django.views import generic
class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'book_detail.html'
    context_object_name = 'book'

class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = 'author_detail.html'
    context_object_name = 'author'


from django.shortcuts import redirect, render
from .forms import CustomUserCreationForm, CustomAuthenticationForm
def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])  # Хранение пароля в зашифрованном виде
            user.save()
            login(request, user)  # Автоматический вход после регистрации
            return redirect('EA:index')
        else:
            print(form.errors)  # Вывод ошибок формы для отладки
    else:
        form = CustomUserCreationForm()

    return render(request, 'registration/register.html', {'form': form})


from .forms import SearchForm
def search(request):
    form = SearchForm()
    results = []

    if request.method == 'GET' and 'query' in request.GET:
        query = request.GET['query']
        results = (Book.objects.filter(title__icontains=query) | Book.objects.filter(author__first_name__icontains=query) | Book.objects.filter(author__last_name__icontains=query) | Book.objects.filter(genre__name__icontains=query))


    return render(request, 'search.html', {'form': form, 'results': results})


def login_user(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('EA:index')
            else:
                form.add_error(None, 'Неверный логин или пароль.')
    else:
        form = CustomAuthenticationForm()

    return render(request, 'registration/login.html', {'form': form})

from django.contrib.auth import login, authenticate, logout
def logout_user(request):
    logout(request)
    return render(request,'registration/logged_out.html')


# API-эндпоинты(конечные точки веб-сервиса, к которой клиентское приложение обращается для выполнения определённых операций или получения данных.):
from rest_framework import generics
from .serializers import BookSerializer, AuthorSerializer

class BookListAPIView(generics.ListAPIView):
    queryset = Book.objects.all()
    serializer_class = BookSerializer

class AuthorListAPIView(generics.ListAPIView):
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer

class BookDetailAPIView(generics.RetrieveAPIView):
    queryset = Book.objects.all()
    serializer_class = BookSerializer

class AuthorDetailAPIView(generics.RetrieveAPIView):
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer


from rest_framework.permissions import IsAdminUser
class AuthorListCreateAPIView(generics.ListCreateAPIView):
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer
    # permission_classes = [IsAdminUser]


class BookListCreateAPIView(generics.ListCreateAPIView):
    queryset = Book.objects.all()
    serializer_class = BookSerializer
    # permission_classes = [IsAdminUser]

    def get_queryset(self):
        queryset = super().get_queryset()
        title = self.request.query_params.get('title', None)
        genre = self.request.query_params.get('genre', None)
        author = self.request.query_params.get('author', None)

        if title:
            queryset = queryset.filter(title__icontains=title)
        if genre:
            queryset = queryset.filter(genre__name__icontains=genre)
        if author:
            queryset = queryset.filter(author__first_name__icontains=author) | queryset.filter(author__last_name__icontains=author)

        return queryset


class BookSearchAPIView(generics.ListAPIView):
    queryset = Book.objects.all()
    serializer_class = BookSerializer

    def get_queryset(self):
        queryset = super().get_queryset()
        title = self.request.query_params.get('title', None)
        genre = self.request.query_params.get('genre', None)
        author = self.request.query_params.get('author', None)

        if title:
            queryset = queryset.filter(title__icontains=title)
        if genre:
            queryset = queryset.filter(genre__name__icontains=genre)
        if author:
            queryset = queryset.filter(author__first_name__icontains=author) | queryset.filter(
                author__last_name__icontains=author)

        return queryset

EP/EA/templates/author_detail.html
{% extends "base.html" %}
{% block title %}<title>Подробная информация о авторе</title>{% endblock %}
{% block content %}
<h1>{{ author.first_name }} {{ author.last_name }}</h1>
<p><strong>Дата рождения:</strong> {{ author.date_of_birth }}</p>
<p><strong>Дата смерти:</strong> {{ author.date_of_death }}</p>
<p><strong>Биография:</strong> {{ author.biography }}</p>
<p><strong>Работы:</strong> {{ author.works }}</p>
<p><strong>Значимые достижения:</strong> {{ author.notable_achievements }}</p>
{% endblock %}

EP/EA/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}{% endblock %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <header>
        <h1>Добро пожаловать на наш сайт!</h1>
        <nav>
            <ul>
                <li><a href="{% url 'EA:index' %}">Главная</a></li>
                <li><a href="{% url 'EA:search' %}">Поиск книг</a></li>
                {% if user.is_authenticated %}
                <form method="post" action="{% url 'EA:logout' %}">
                    {% csrf_token %}
                    <button type="submit">Выйти</button>
                </form>
                {% else %}
                <li><a href="{% url 'EA:login' %}">Войти</a></li>
                <li>Нет аккаунта? <a href="{% url 'EA:register' %}">Зарегистрируйтесь!</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

    <div class="container">
        <main>
            {% block content %}
            <!-- Основное содержимое страницы будет здесь -->
            {% endblock %}
        </main>
    </div>

    <footer>
        <p>&copy; 2024 Design.pro</p>
    </footer>

</body>
</html>

EP/EA/templates/book_detail.html
{% extends "base.html" %}
{% block title %}<title>Подробная информация о книге</title>{% endblock %}
{% block content %}
<h1>{{ book.title }}</h1>
{% if book.cover_image %}
    <img src="{{ book.cover_image.url }}" alt="Cover Image">
{% endif %}
<p><strong>Автор:</strong> <a href="{% url 'EA:author-detail' book.author.id %}">{{ book.author.first_name }} {{ book.author.last_name }}</a></p>
<p><strong>Жанр:</strong> {{ book.display_genre }}</p>
<p><strong>Описание:</strong> {{ book.summary }}</p>
<p><strong>ISBN:</strong> {{ book.isbn }}</p>
<p><strong>Год публикации:</strong> {{ book.publication_year }}</p>
<p><strong>Издатель:</strong> {{ book.publisher }}</p>
{% endblock %}

EP/EA/templates/create_book.html
{% extends "base.html" %}

{% block title %}<title>Добавление книги</title>{% endblock %}
{% block content %}
<h1>Добавить книгу</h1>
    <form method="post">
    {% csrf_token %}
    {{ form.first_name.label_tag }} {{ form.first_name }}<br>
    {{ form.last_name.label_tag }} {{ form.last_name }}<br>
    {{ form.title.label_tag }} {{ form.title }}<br>
    {{ form.publisher.label_tag }} {{ form.publisher }}<br>
    {{ form.publication_year.label_tag }} {{ form.publication_year }}<br>
    {{ form.type.label_tag }} {{ form.type }}<br>
    <button type="submit">Добавить книгу</button>
</form>
    {% if form.errors %}
        <div>
            <h3>Ошибки:</h3>
            <ul>
                {% for field in form %}
                    {% for error in field.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
{% endblock %}

EP/EA/templates/index.html
{% extends "base.html" %}

{% block title %}<title>Главная страница</title>{% endblock %}
{% block content %}
<h1>Интересная информация сайта</h1>

  <ul>
    <li><strong>Кол-во жанров:</strong> {{ num_genres }}</li>
    <li><strong>Кол-во книг со словом "дети" в названии:</strong> {{ num_books_word }}</li>
    <li><strong>Кол-во книг:</strong> {{ num_books }}</li>
    <li><strong>Кол-во копий книг:</strong> {{ num_instances }}</li>
    <li><strong>Кол-во доуступных копий книг:</strong> {{ num_instances_available }}</li>
    <li><strong>Кол-во авторов:</strong> {{ num_authors }}</li>
  </ul>

<p>
  Вы посетили эту страницу {{ num_visits }}{% if num_visits == 1 %} time{% else %} раз{% endif %}.
</p>
{% endblock %}

EP/EA/templates/search.html
{% extends "base.html" %}
{% block title %}<title>Страница поиска</title>{% endblock %}
{% block content %}
<h1>Результаты поиска</h1>
<form method="get" action="{% url 'EA:search' %}">
    {{ form.as_p }}
    <button type="submit">Поиск</button>
</form>

<ul>
    {% for book in results %}
        <li>
            <a href="{% url 'EA:book-detail' book.id %}">{{ book.title }}</a> - {{ book.author.first_name }} {{ book.author.last_name }}
        </li>
    {% empty %}
        <li>Ничего не найдено.</li>
    {% endfor %}
</ul>
{% endblock %}